"""Add UserProduct association and update Product model

Revision ID: 7bb361acaf09
Revises: 772e83573ee1
Create Date: 2024-12-16 02:50:55.115722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb361acaf09'
down_revision = '772e83573ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='_user_product_uc')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    op.drop_table('user_products')
    # ### end Alembic commands ###
